using HarmonyLib;
using MegaCrit.Sts2.Core.Localization;
using System.Collections.Generic;

namespace shirubimod.Scripts.Patches;

// 目前我们没有加载 PCK，所以不能靠 localization/*.json 给新内容提供文本。
// 这个补丁会在游戏读取本地化 key 时，先检查希比 mod 自己的文本表。
[HarmonyPatch(typeof(LocTable), nameof(LocTable.GetRawText))]
public static class ShirubiLocalizationPatch
{
    // key 的规则：
    // 角色文本来自 RitsuLib 自动生成的角色 ID，例如 SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.title。
    // 卡牌文本来自 [RegisterCard(..., FullPublicEntry = "...")]，例如 SHIBI_STRIKE.title。
    // 描述中的 {Damage:diff()}、{Block:diff()}、{Cards:diff()} 会读取卡牌里的 DynamicVar。
    private static readonly Dictionary<string, string> Text = new()
    {
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.title"] = "希比",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.titleObject"] = "希比",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.description"] = "异世界最强的魔法师，但她认为用刀战斗更炫酷！\n如果她决定在涅奥处回想起一切...\n将鼠标悬停在魔力全开按钮上查看希比的核心机制",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.cardsModifierTitle"] = "希比卡牌",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.cardsModifierDescription"] = "希比卡牌现在会出现在奖励和商店中。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.eventDeathPrevention"] = "这下玩大了，事已至此先润吧。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.goldMonologue"] = "[sine]好耶，是金币！能带出去作纪念吗~[/sine]",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.aromaPrinciple"] = "[sine][purple]一只可爱的狐耳娘进入了高塔。[/purple][/sine]",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.banter.alive.endTurnPing"] = "准备好了。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.banter.dead.endTurnPing"] = "...",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.possessiveAdjective"] = "她的",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.pronounObject"] = "她",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.pronounPossessive"] = "她的",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.pronounSubject"] = "她",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.unlockText"] = "进行一局游戏以解锁该角色。",

        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.0-0r.ancient"] = "Another one climbing this tower?",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.0-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.0-1r.char"] = "I am Shirubi. I came this far for my own answer.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.0-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.0-2r.ancient"] = "Then show me what that answer is worth.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.1-0r.ancient"] = "You again.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.1-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.1-1r.char"] = "This time, I will cut through the ending.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.1-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.1-2r.ancient"] = "Try.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.2-0r.ancient"] = "How many times will you return?",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.2-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.2-1r.char"] = "Until the story reaches the page I chose.",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.2-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER.2-2r.ancient"] = "Then begin.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.0-0r.ancient"] = "Another one climbing this tower?",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.0-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.0-1r.char"] = "I am Shirubi. I came this far for my own answer.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.0-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.0-2r.ancient"] = "Then show me what that answer is worth.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.1-0r.ancient"] = "You again.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.1-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.1-1r.char"] = "This time, I will cut through the ending.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.1-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.1-2r.ancient"] = "Try.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.2-0r.ancient"] = "How many times will you return?",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.2-0r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.2-1r.char"] = "Until the story reaches the page I chose.",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.2-1r.next"] = "Continue",
        ["THE_ARCHITECT.talk.SHIRUBI_CHARACTER.2-2r.ancient"] = "Then begin.",

        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER2_EPOCH.title"] = "希比 II",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER2_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER2_EPOCH.unlockText"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER3_EPOCH.title"] = "希比 III",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER3_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER3_EPOCH.unlockText"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER4_EPOCH.title"] = "希比 IV",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER4_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER4_EPOCH.unlockText"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER5_EPOCH.title"] = "希比 V",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER5_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER5_EPOCH.unlockText"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER6_EPOCH.title"] = "希比 VI",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER6_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER6_EPOCH.unlockText"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER7_EPOCH.title"] = "希比 VII",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER7_EPOCH.description"] = "希比的临时时间线占位。",
        ["SHIRUBIMOD_CHARACTER_SHIRUBI_CHARACTER7_EPOCH.unlockText"] = "希比的临时时间线占位。",

        ["SHIRUBI_FULL_RELEASE_BUTTON.title"] = "希比机制",
        ["SHIRUBI_FULL_RELEASE_BUTTON.description"] = "希比的部分攻击卡带有打断词条：\n看破：打断进攻。\n破铠：打断添加格挡。\n沉默：打断施加状态和添加手牌。\n\n怪物会根据等级获得韧性条：\n小怪2点，精英3点，Boss4点。\n受到相应点数的打断攻击后，怪物会被击晕。\n怪物被击晕后，韧性条会有一回合封锁，无法再次被击晕。\n\n怪物被击晕后，希比会获得奖励或 buff，一些能力牌也会给予额外 buff。\n小怪/精英/Boss 被击晕后，希比获得 1/1/2 点能量，并抽 1/2/3 张牌。\n\n希比的部分卡带有“魔力”词条，打出后会给予玛娜。\n当玛娜达到17点后，可手动开启“魔力全开”状态。\n开启魔力全开时，从抽牌堆中抽出3张带有“魔力”的卡，并获得3点能量。\n魔力全开状态下，所有带有“魔力”的卡会解放更强力的效果，但不会再获得玛娜。\n魔力全开状态下打出七张带有“魔力”的卡牌后，魔力全开状态消失。",

        ["SHIBI_GOLDEN_BUTTERFLY_KNOT.title"] = "金色蝴蝶结",
        ["SHIBI_GOLDEN_BUTTERFLY_KNOT.description"] = "每回合开始时，获得{Mana:diff()}点[gold]玛娜[/gold]。\n每拥有{ManaPerBuff:diff()}点[gold]玛娜[/gold]，获得{Strength:diff()}点[gold]力量[/gold]和{Dexterity:diff()}点[gold]敏捷[/gold]。\n当你将要死亡时，回复最大生命值{Heal:diff()}%的生命，并获得{FullRelease:diff()}次[gold]魔力全开[/gold]。",
        ["SHIBI_GOLDEN_BUTTERFLY_KNOT.flavor"] = "漂亮、醒目，而且显然藏着一点离谱的魔力。",
        ["SHIBI_SHION_HAIRPIN.title"] = "雪音的发卡",
        ["SHIBI_SHION_HAIRPIN.description"] = "每回合开始时，获得{MagicEye:diff()}层[gold]魔眼[/gold]。",
        ["SHIBI_SHION_HAIRPIN.flavor"] = "她总是说，要看清敌人的意图再行动，我又不傻。",
        ["SHIBI_HER_MEMORY_WORLD_MEMORY.title"] = "她的记忆，世界的记忆",
        ["SHIBI_HER_MEMORY_WORLD_MEMORY.description"] = "这是你自己走上的道路，这是你自己选择的命运",
        ["SHIBI_HER_MEMORY_WORLD_MEMORY.flavor"] = "我会陪在你身边，直至宇宙的意志消散。",
        ["SHIRUBI_NEOW_MEMORY_OPTION.title"] = "希比决定回想起一切。",
        ["SHIRUBI_NEOW_MEMORY_OPTION.description"] = "获得[gold]她的记忆，世界的记忆[/gold]。",

        ["SHIBI_STRIKE.title"] = "斩断",
        ["SHIBI_STRIKE.description"] = "造成{Damage:diff()}点伤害。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：额外造成3点伤害。",
        ["SHIBI_DEFEND.title"] = "格挡",
        ["SHIBI_DEFEND.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：额外获得3点[gold]格挡[/gold]。",
        ["SHIBI_NEEDLE_THRUST.title"] = "雷鸣突刺",
        ["SHIBI_NEEDLE_THRUST.description"] = "造成{Damage:diff()}点伤害。\n抽{Cards:diff()}张牌。\n获得2点[gold]玛娜[/gold]。\n[gold]看破[/gold]：打断进攻。\n[gold]魔力全开[/gold]：额外造成3点伤害，额外抽1张牌。",
        ["SHIBI_GUARDED_STEP.title"] = "中场休息",
        ["SHIBI_GUARDED_STEP.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n抽{Cards:diff()}张牌。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：额外获得3点[gold]格挡[/gold]，额外抽1张牌。\n*是时候来一把特昆牌了",
        ["SHIBI_BRIGHT_CUT.title"] = "百裂斩",
        ["SHIBI_BRIGHT_CUT.description"] = "造成{Damage:diff()}点伤害3次。\n[gold]破铠[/gold]：打断添加格挡。\n[gold]魔力全开[/gold]：每段额外造成2点伤害。",
        ["SHIBI_BUTTERFLY_GUARD.title"] = "魔法护值",
        ["SHIBI_BUTTERFLY_GUARD.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：额外获得5点[gold]格挡[/gold]。",
        ["SHIBI_QUICK_STUDY.title"] = "制衡",
        ["SHIBI_QUICK_STUDY.description"] = "抽{Cards:diff()}张牌。\n丢弃{Cards:diff()}张牌。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：抽弃数量额外+1。\n*那好啊，我抽牌我也弃牌",
        ["SHIBI_DOUBLE_FLICKER.title"] = "反砍",
        ["SHIBI_DOUBLE_FLICKER.description"] = "造成{Damage:diff()}点伤害两次。\n获得1点[gold]玛娜[/gold]。\n[gold]沉默[/gold]：打断状态类意图。\n[gold]魔力全开[/gold]：改为造成三次。\n*我砍两刀",
        ["SHIBI_FULL_RELEASE.title"] = "魔力全开",
        ["SHIBI_FULL_RELEASE.description"] = "如果你至少有17点[gold]玛娜[/gold]，消耗17点[gold]玛娜[/gold]，获得7次[gold]魔力全开[/gold]。\n抽3张带有[gold]魔力[/gold]的牌。\n获得3点能量。",

        ["SHIBI_WEAKNESS_INSIGHT.title"] = "弱点看破",
        ["SHIBI_WEAKNESS_INSIGHT.description"] = "获得1层[gold]魔眼[/gold]。",
        ["SHIBI_HAPPY_WATER.title"] = "快乐水",
        ["SHIBI_HAPPY_WATER.description"] = "获得1点能量。\n获得1点[gold]玛娜[/gold]。{IfUpgraded:show:\n抽1张牌。|}",
        ["SHIBI_UNO_PLUS_TWO.title"] = "UNO+2",
        ["SHIBI_UNO_PLUS_TWO.description"] = "抽2张牌。\n[gold]魔力全开[/gold]：改为抽4张牌。",
        ["SHIBI_SHADOW_IMAGE.title"] = "现影",
        ["SHIBI_SHADOW_IMAGE.description"] = "下一张牌额外打出1次。",
        ["SHIBI_YOU_GIVE_LUDA.title"] = "你给路大有",
        ["SHIBI_YOU_GIVE_LUDA.description"] = "获得1层[gold]无实体[/gold]。\n每拥有1层[gold]魔眼[/gold]，本牌费用-1。{IfUpgraded:show:\n获得1层[gold]敏捷[/gold]。|}",
        ["SHIBI_LIFE_LIGHT.title"] = "灵命光",
        ["SHIBI_LIFE_LIGHT.description"] = "获得{PlatedArmor:diff()}层[gold]覆甲[/gold]。\n[gold]魔力全开[/gold]：改为获得{IfUpgraded:show:9|7}层[gold]覆甲[/gold]。",
        ["SHIBI_METEOR.title"] = "陨星",
        ["SHIBI_METEOR.description"] = "给予敌人{IfUpgraded:show:3|1}层[gold]易伤[/gold]。\n解除其[gold]韧性封锁[/gold]。\n获得1点[gold]玛娜[/gold]。",
        ["SHIBI_MY_TURN.title"] = "我的回合",
        ["SHIBI_MY_TURN.description"] = "若本回合击晕过敌人，抽{IfUpgraded:show:3|2}张牌，获得3点能量。",
        ["SHIBI_STILL_MY_TURN.title"] = "还是我的回合",
        ["SHIBI_STILL_MY_TURN.description"] = "若本回合击晕过敌人，获得{IfUpgraded:show:17|12}点[gold]玛娜[/gold]。",
        ["SHIBI_DIRECT_MAGIC_EYE.title"] = "直破之魔眼",
        ["SHIBI_DIRECT_MAGIC_EYE.description"] = "下回合获得1层[gold]魔眼[/gold]。\n给予敌人1层[gold]易伤[/gold]。{IfUpgraded:show:\n给予敌人1层[gold]虚弱[/gold]。|}",
        ["SHIBI_TACTICAL_RETREAT.title"] = "战术撤退",
        ["SHIBI_TACTICAL_RETREAT.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n选择1张手牌，本场战斗中其费用-1。",
        ["SHIBI_TACTICAL_RETREAT.selectionScreenPrompt"] = "选择1张手牌，本场战斗中费用-1。",
        ["SHIBI_WHAT_TO_EAT.title"] = "吃什么",
        ["SHIBI_WHAT_TO_EAT.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n将1张带有[gold]消耗[/gold]和[gold]虚无[/gold]的[gold]是啊，吃什么{IfUpgraded:show:+|}[/gold]加入手牌。",
        ["SHIBI_YEAH_WHAT_TO_EAT.title"] = "是啊，吃什么",
        ["SHIBI_YEAH_WHAT_TO_EAT.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n将1张带有[gold]消耗[/gold]和[gold]虚无[/gold]的[gold]吃什么{IfUpgraded:show:+|}[/gold]加入手牌。",
        ["SHIBI_DONE_AND_GONE.title"] = "搞定就撤",
        ["SHIBI_DONE_AND_GONE.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。",
        ["SHIBI_BUT_THAT_IS_LOSER_THINKING.title"] = "但这是废物的思维",
        ["SHIBI_BUT_THAT_IS_LOSER_THINKING.description"] = "获得1层[gold]力量[/gold]。\n获得1层[gold]易伤[/gold]。{IfUpgraded:show:\n抽1张牌。|}",
        ["SHIBI_ISEKAI_FARMSTAY.title"] = "异世界农家乐",
        ["SHIBI_ISEKAI_FARMSTAY.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n给予敌人3层[gold]虚弱[/gold]。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：改为获得{FullReleaseBlock:diff()}点[gold]格挡[/gold]。",
        ["SHIBI_NINE_TAIL_FUNERAL.title"] = "九尾烈葬",
        ["SHIBI_NINE_TAIL_FUNERAL.description"] = "造成{Damage:diff()}点伤害X次。\n获得3点[gold]玛娜[/gold]。\n[gold]消耗[/gold]。\n[gold]魔力全开[/gold]：伤害次数+1。",
        ["SHIBI_CURSE_POWER_RELEASE.title"] = "咒力释放",
        ["SHIBI_CURSE_POWER_RELEASE.description"] = "造成{Damage:diff()}点伤害。\n若命中被[gold]眩晕[/gold]的敌人，获得1点能量。",
        ["SHIBI_WAND_THOUSAND_ARRAY.title"] = "魔杖千阵",
        ["SHIBI_WAND_THOUSAND_ARRAY.description"] = "造成{Damage:diff()}点伤害。\n获得{IfUpgraded:show:4|3}点[gold]玛娜[/gold]。\n[gold]消耗[/gold]。\n[gold]魔力全开[/gold]：改为造成2次。",
        ["SHIBI_FLUFFY_TAIL.title"] = "毛绒绒的尾巴",
        ["SHIBI_FLUFFY_TAIL.description"] = "造成{Damage:diff()}点伤害。\n[gold]沉默[/gold]：打断状态类意图。\n获得{IfUpgraded:show:3|2}点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：获得1层[gold]魔眼[/gold]。",
        ["SHIBI_SKY_FALL.title"] = "天空坠落",
        ["SHIBI_SKY_FALL.description"] = "选择并[gold]消耗[/gold]1张手牌。\n造成{Damage:diff()}点伤害。\n获得{IfUpgraded:show:5|3}点[gold]玛娜[/gold]。\n[gold]消耗[/gold]。\n[gold]魔力全开[/gold]：伤害+17。",
        ["SHIBI_SKY_FALL.selectionScreenPrompt"] = "选择1张手牌消耗。",
        ["SHIBI_SUPER_MAGIC_CANNON.title"] = "超魔法能炮",
        ["SHIBI_SUPER_MAGIC_CANNON.description"] = "选择并丢弃1张手牌。\n造成{Damage:diff()}点伤害。\n若击杀敌人，抽1张牌。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：伤害+7。",
        ["SHIBI_SUPER_MAGIC_CANNON.selectionScreenPrompt"] = "选择1张手牌丢弃。",
        ["SHIBI_FOX_SHOVEL.title"] = "狐一铲",
        ["SHIBI_FOX_SHOVEL.description"] = "造成{Damage:diff()}点伤害。\n[gold]看破[/gold]：打断进攻。\n若本次击晕敌人，获得1点能量。",
        ["SHIBI_FOXTRAAK.title"] = "Foxtraak",
        ["SHIBI_FOXTRAAK.description"] = "将3张[gold]弑魔魔法{IfUpgraded:show:+|}[/gold]加入手牌。",
        ["SHIBI_DEMON_SLAYING_MAGIC.title"] = "弑魔魔法",
        ["SHIBI_DEMON_SLAYING_MAGIC.description"] = "造成{Damage:diff()}点伤害。\n本回合每使用1张[gold]弑魔魔法[/gold]，同名卡费用+1。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：改为造成2次。",
        ["SHIBI_I_AM_MANAMIC.title"] = "I am Manamic",
        ["SHIBI_I_AM_MANAMIC.description"] = "对所有敌人造成{Damage:diff()}点伤害。\n本场战斗每[gold]消耗[/gold]过1张带有[gold]魔力[/gold]的牌，本牌费用-1。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：伤害次数+1。",
        ["SHIBI_SONIC_BLADE.title"] = "音速之刃",
        ["SHIBI_SONIC_BLADE.description"] = "造成{Damage:diff()}点伤害。\n获得{Block:diff()}点[gold]格挡[/gold]。\n[gold]消耗[/gold]。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：伤害+5，格挡+5。",
        ["SHIBI_WHITE_FOX_STAR.title"] = "白狐之星",
        ["SHIBI_WHITE_FOX_STAR.description"] = "造成1次{Damage:diff()}点伤害。\n本回合每打出1张攻击牌，伤害+1。\n本回合每打出1张技能牌，次数+1。\n[gold]魔力全开[/gold]：基础伤害和次数+1。",
        ["SHIBI_KUNLAN_ICE_FLAME.title"] = "坤蓝冰焰",
        ["SHIBI_KUNLAN_ICE_FLAME.description"] = "选择并[gold]消耗[/gold]1张手牌。\n获得1点能量。\n[gold]虚无[/gold]。",
        ["SHIBI_KUNLAN_ICE_FLAME.selectionScreenPrompt"] = "选择1张手牌消耗。",
        ["SHIBI_GOLDEN_EARS_DOUBLE_SPEED.title"] = "金色有耳两倍速",
        ["SHIBI_GOLDEN_EARS_DOUBLE_SPEED.description"] = "丢弃至多2张手牌。\n从抽牌堆中抽取1张带有[gold]魔力[/gold]的牌。",
        ["SHIBI_GOLDEN_EARS_DOUBLE_SPEED.selectionScreenPrompt"] = "选择至多2张手牌丢弃。",
        ["SHIBI_FOX_BREATH.title"] = "狐之呼吸",
        ["SHIBI_FOX_BREATH.description"] = "选择并[gold]消耗[/gold]1张手牌。\n抽{Cards:diff()}张牌。\n[gold]消耗[/gold]。\n获得1点[gold]玛娜[/gold]。",
        ["SHIBI_FOX_BREATH.selectionScreenPrompt"] = "选择1张手牌消耗。",
        ["SHIBI_APPLE_STAND.title"] = "苹果摊",
        ["SHIBI_APPLE_STAND.description"] = "本回合每打出{IfUpgraded:show:3|4}张牌，下回合开始多抽1张牌。\n[gold]消耗[/gold]。",
        ["SHIBI_WOULD_YOU_LIKE_FOX.title"] = "请问您今天要来点狐狸吗",
        ["SHIBI_WOULD_YOU_LIKE_FOX.description"] = "阻止下1次你受到的生命值损伤。",
        ["SHIBI_SLEEP_WELL.title"] = "好好睡好好睡",
        ["SHIBI_SLEEP_WELL.description"] = "获得{IfUpgraded:show:4|3}层[gold]再生[/gold]。\n立刻结束本回合。\n获得2点[gold]玛娜[/gold]。\n[gold]消耗[/gold]。",
        ["SHIBI_NO_FOX_NO_LIFE.title"] = "No Fox No Life",
        ["SHIBI_NO_FOX_NO_LIFE.description"] = "将1张费用-1，带有[gold]看破[/gold]的临时卡加入手牌。{IfUpgraded:show:\n获得1层[gold]魔眼[/gold]。|}",
        ["SHIBI_STEINS_GATE_CHOICE.title"] = "命运石之门的选择",
        ["SHIBI_STEINS_GATE_CHOICE.description"] = "随机丢弃2张手牌。\n将弃牌堆顶部2张牌移入手牌。\n将抽牌堆顶部2张牌放入弃牌堆。",
        ["SHIBI_FOXMIZAWA_SYNDROME.title"] = "狐见泽综合征",
        ["SHIBI_FOXMIZAWA_SYNDROME.description"] = "给予敌人{IfUpgraded:show:3|2}层[gold]虚弱[/gold]。\n场上每有1个敌方目标，使其失去1点[gold]力量[/gold]。",
        ["SHIBI_SEVENFOLD_MAGIC_CIRCLE.title"] = "魔天狐七重法阵",
        ["SHIBI_SEVENFOLD_MAGIC_CIRCLE.description"] = "获得{Block:diff()}点[gold]格挡[/gold]。\n获得3点[gold]玛娜[/gold]。\n[gold]消耗[/gold]。",
        ["SHIBI_ROUND_FOX_PRINCIPLE.title"] = "圆狐之理",
        ["SHIBI_ROUND_FOX_PRINCIPLE.description"] = "每5回合获得1层[gold]无实体[/gold]。\n使用[gold]魔力全开[/gold]后，立刻获得1层[gold]无实体[/gold]。",
        ["SHIBI_MANA_RESEARCH.title"] = "魔力研究",
        ["SHIBI_MANA_RESEARCH.description"] = "本回合每打出2张带有[gold]魔力[/gold]的牌，获得1点[gold]玛娜[/gold]和1点[gold]力量[/gold]。",
        ["SHIBI_RAGING_MAGIC.title"] = "狂暴魔法",
        ["SHIBI_RAGING_MAGIC.description"] = "本回合带有[gold]魔力[/gold]的攻击牌费用+1，攻击伤害+4。",
        ["SHIBI_FLAME_SWORD_DANCE.title"] = "焰剑仙舞",
        ["SHIBI_FLAME_SWORD_DANCE.description"] = "造成{Damage:diff()}点伤害3次。\n[gold]沉默[/gold]：打断状态类意图。\n获得1点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：改为造成12点伤害3次。",
        ["SHIBI_SWORD_OF_BENEVOLENCE.title"] = "仁之剑",
        ["SHIBI_SWORD_OF_BENEVOLENCE.description"] = "造成{Damage:diff()}点伤害。\n给予敌人2层[gold]虚弱[/gold]。\n将1张带有[gold]消耗[/gold]和[gold]虚无[/gold]的[gold]义之剑{IfUpgraded:show:+|}[/gold]加入手牌。",
        ["SHIBI_SWORD_OF_JUSTICE.title"] = "义之剑",
        ["SHIBI_SWORD_OF_JUSTICE.description"] = "造成{Damage:diff()}点伤害。\n给予敌人2层[gold]易伤[/gold]。\n将1张带有[gold]消耗[/gold]和[gold]虚无[/gold]的[gold]仁之剑{IfUpgraded:show:+|}[/gold]加入手牌。",
        ["SHIBI_PUMPKIN_PIE.title"] = "南瓜派",
        ["SHIBI_PUMPKIN_PIE.description"] = "造成{Damage:diff()}点伤害。\n获得{IfUpgraded:show:7|5}点[gold]玛娜[/gold]。\n*是谁把这东西塞到我的卡组里的？！",
        ["SHIBI_IAIDO_PURPLE_LIGHTNING.title"] = "拔刀紫电",
        ["SHIBI_IAIDO_PURPLE_LIGHTNING.description"] = "造成{Damage:diff()}点伤害。\n[gold]破铠[/gold]：打断添加格挡。",
        ["SHIBI_HEAVEN_EARTH_FLASH.title"] = "天地一闪",
        ["SHIBI_HEAVEN_EARTH_FLASH.description"] = "造成{Damage:diff()}点伤害。\n[gold]看破[/gold]：打断进攻。",
        ["SHIBI_INSTANT_STRIKE.title"] = "瞬击",
        ["SHIBI_INSTANT_STRIKE.description"] = "造成{Damage:diff()}点伤害。\n[gold]破铠[/gold]：打断添加格挡。",
        ["SHIBI_CURSE_KILLING_BLADE.title"] = "咒杀刀",
        ["SHIBI_CURSE_KILLING_BLADE.description"] = "造成{Damage:diff()}点伤害。\n[gold]沉默[/gold]：打断状态类意图。{IfUpgraded:show:\n给予敌人1层[gold]易伤[/gold]。|}",
        ["SHIBI_HITTER.title"] = "击手",
        ["SHIBI_HITTER.description"] = "造成{Damage:diff()}点伤害。\n[gold]看破[/gold]：打断进攻。",
        ["SHIBI_DIMENSION_SLASH.title"] = "次元斩",
        ["SHIBI_DIMENSION_SLASH.description"] = "对所有敌人造成{Damage:diff()}点伤害。\n本场战斗中每击晕过1名敌人，本牌费用-1。\n获得1点[gold]玛娜[/gold]。",
        ["SHIBI_SKY_BREAKING_SLASH.title"] = "破空斩",
        ["SHIBI_SKY_BREAKING_SLASH.description"] = "造成{Damage:diff()}点伤害。\n获得{Block:diff()}点[gold]格挡[/gold]。{IfUpgraded:show:\n给予敌人1层[gold]虚弱[/gold]。|}",
        ["SHIBI_EXPLOSIVE_FIREBALL.title"] = "爆炎弹",
        ["SHIBI_EXPLOSIVE_FIREBALL.description"] = "造成{Damage:diff()}点伤害3次。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：改为对所有敌人造成{FullReleaseDamage:diff()}点伤害3次。",
        ["SHIBI_FLAME_IMPACT.title"] = "火焰冲击",
        ["SHIBI_FLAME_IMPACT.description"] = "造成{Damage:diff()}点伤害2次。\n获得2点[gold]玛娜[/gold]。\n[gold]魔力全开[/gold]：改为造成7点伤害2次。",
        ["SHIBI_ICE_BLOOM.title"] = "寒冰绽放",
        ["SHIBI_ICE_BLOOM.description"] = "对所有敌人造成{Damage:diff()}点伤害。\n获得2点[gold]玛娜[/gold]。{IfUpgraded:show:\n获得3点[gold]格挡[/gold]。|}\n[gold]魔力全开[/gold]：额外对所有敌人造成1点削韧。",
        ["SHIBI_EXTREME_COLD_ICE_SPIKE.title"] = "极寒冰刺",
        ["SHIBI_EXTREME_COLD_ICE_SPIKE.description"] = "造成{Damage:diff()}点伤害4次。\n获得2点[gold]玛娜[/gold]。{IfUpgraded:show:\n给予敌人1层[gold]虚弱[/gold]。|}\n[gold]魔力全开[/gold]：改为对所有敌人造成1点伤害7次。",
        ["SHIBI_ANNIHILATION_BLACK_HOLE.title"] = "湮灭黑洞",
        ["SHIBI_ANNIHILATION_BLACK_HOLE.description"] = "造成2点伤害5次。\n获得3点[gold]玛娜[/gold]。{IfUpgraded:show:\n给予敌人1层[gold]虚弱[/gold]。|}\n[gold]魔力全开[/gold]：费用+1，改为对所有敌人造成{Damage:diff()}点伤害7次。",
        ["SHIBI_FULL_COMBO.title"] = "fullcombo",
        ["SHIBI_FULL_COMBO.description"] = "每次击晕敌人时，抽1张牌，获得1点能量。",
        ["SHIBI_FOX_SPIRIT_INTUITION.title"] = "狐妖直觉",
        ["SHIBI_FOX_SPIRIT_INTUITION.description"] = "获得{IfUpgraded:show:2|3}层[gold]狐妖直觉[/gold]。\n每受到{IfUpgraded:show:2|3}次怪物攻击获得1层[gold]魔眼[/gold]。",
        ["SHIBI_HARDENING_PATTERN.title"] = "硬化之纹",
        ["SHIBI_HARDENING_PATTERN.description"] = "每回合开始获得{IfUpgraded:show:5|3}点[gold]格挡[/gold]。\n每有3点[gold]玛娜[/gold]，额外获得1点[gold]格挡[/gold]。",
        ["SHIBI_HEROIC_SEAL.title"] = "豪气之印",
        ["SHIBI_HEROIC_SEAL.description"] = "每回合开始获得1点[gold]力量[/gold]。\n[gold]魔力全开[/gold]：改为每回合开始获得2点[gold]力量[/gold]。",
        ["SHIBI_MANA_ABSORB.title"] = "玛娜吸收",
        ["SHIBI_MANA_ABSORB.description"] = "本场战斗中，你获得的[gold]玛娜[/gold]数量+1。",

        ["SHIBI_PAINFUL_PAST.title"] = "沉痛的过去",
        ["SHIBI_PAINFUL_PAST.description"] = "给予所有敌人{Amount:diff()}层[gold]虚弱[/gold]和{Amount:diff()}层[gold]易伤[/gold]。\n所有敌人失去{Amount:diff()}层[gold]力量[/gold]和{Amount:diff()}层[gold]敏捷[/gold]。",
        ["SHIBI_BEGINNING_OF_STORY.title"] = "故事的开篇",
        ["SHIBI_BEGINNING_OF_STORY.description"] = "获得{Amount:diff()}层[gold]力量[/gold]和{Amount:diff()}层[gold]敏捷[/gold]。",
        ["SHIBI_TWISTING_JOURNEY.title"] = "波折的旅途",
        ["SHIBI_TWISTING_JOURNEY.description"] = "抽{Cards:diff()}张牌。\n使用后回到手牌。",
        ["SHIBI_HAPPY_ENDING.title"] = "圆满的结局",
        ["SHIBI_HAPPY_ENDING.description"] = "治疗{Heal:diff()}点生命。\n获得{Energy:diff()}点能量。",
        ["SHIBI_START_END_COMPLETE_ME.title"] = "起点，终点，完整的我",
        ["SHIBI_START_END_COMPLETE_ME.description"] = "获得{Amount:diff()}层[gold]无实体[/gold]。",
        ["SHIBI_TERMINUS_OF_ALL.title"] = "将一切化作终焉",
        ["SHIBI_TERMINUS_OF_ALL.description"] = "造成{Damage:diff()}点伤害。",
        ["SHIBI_RESHAPE_WORLD_WITH_MEMORY.title"] = "以记忆重塑世界",
        ["SHIBI_RESHAPE_WORLD_WITH_MEMORY.description"] = "[gold]不可打出[/gold]。\n[gold]保留[/gold]。\n无效果。",

        ["SHIRUBIMOD_POWER_SHIBI_MANA_POWER.title"] = "玛娜",
        ["SHIRUBIMOD_POWER_SHIBI_MANA_POWER.description"] = "希比积攒的魔力资源。\n达到17点后，可以开启[gold]魔力全开[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_FULL_RELEASE_POWER.title"] = "魔力全开",
        ["SHIRUBIMOD_POWER_SHIBI_FULL_RELEASE_POWER.description"] = "带有[gold]魔力[/gold]的卡牌会释放更强效果，但不会再获得[gold]玛娜[/gold]。\n每打出一张带有[gold]魔力[/gold]的牌，层数减少1。",
        ["SHIRUBIMOD_POWER_SHIBI_TOUGHNESS_POWER.title"] = "韧性",
        ["SHIRUBIMOD_POWER_SHIBI_TOUGHNESS_POWER.description"] = "受到匹配意图的[gold]打断[/gold]攻击时减少1点。\n归零时被[gold]击晕[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_TOUGHNESS_LOCK_POWER.title"] = "韧性封锁",
        ["SHIRUBIMOD_POWER_SHIBI_TOUGHNESS_LOCK_POWER.description"] = "下一次怪物行动前无法再次被[gold]击晕[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_MAGIC_EYE_POWER.title"] = "魔眼",
        ["SHIRUBIMOD_POWER_SHIBI_MAGIC_EYE_POWER.description"] = "下一次攻击额外削减1点[gold]韧性[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_NEXT_TURN_MAGIC_EYE_POWER.title"] = "直破之魔眼",
        ["SHIRUBIMOD_POWER_SHIBI_NEXT_TURN_MAGIC_EYE_POWER.description"] = "下回合开始时，获得[gold]魔眼[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_FULL_COMBO_POWER.title"] = "fullcombo",
        ["SHIRUBIMOD_POWER_SHIBI_FULL_COMBO_POWER.description"] = "每次击晕敌人时，抽1张牌，获得1点能量。",
        ["SHIRUBIMOD_POWER_SHIBI_MANA_RESEARCH_POWER.title"] = "魔力研究",
        ["SHIRUBIMOD_POWER_SHIBI_MANA_RESEARCH_POWER.description"] = "本回合每打出2张带有[gold]魔力[/gold]的牌，获得[gold]玛娜[/gold]和[gold]力量[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_RAGING_MAGIC_POWER.title"] = "狂暴魔法",
        ["SHIRUBIMOD_POWER_SHIBI_RAGING_MAGIC_POWER.description"] = "本回合带有[gold]魔力[/gold]的攻击牌费用+1，攻击伤害提高。",
        ["SHIRUBIMOD_POWER_SHIBI_FOX_SPIRIT_INTUITION_POWER.title"] = "狐妖直觉",
        ["SHIRUBIMOD_POWER_SHIBI_FOX_SPIRIT_INTUITION_POWER.description"] = "每受到1次怪物攻击，层数-1。\n归零时获得1层[gold]魔眼[/gold]，然后重回3层。",
        ["SHIRUBIMOD_POWER_SHIBI_MANA_ABSORB_POWER.title"] = "玛娜吸收",
        ["SHIRUBIMOD_POWER_SHIBI_MANA_ABSORB_POWER.description"] = "获得的[gold]玛娜[/gold]数量增加。",
        ["SHIRUBIMOD_POWER_SHIBI_ROUND_FOX_PRINCIPLE_POWER.title"] = "圆狐之理",
        ["SHIRUBIMOD_POWER_SHIBI_ROUND_FOX_PRINCIPLE_POWER.description"] = "倒计时归零时，获得1层[gold]无实体[/gold]，然后重置为5。\n使用[gold]魔力全开[/gold]后，立刻获得1层[gold]无实体[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_NEXT_TURN_DRAW_POWER.title"] = "下回合抽牌",
        ["SHIRUBIMOD_POWER_SHIBI_NEXT_TURN_DRAW_POWER.description"] = "下回合开始时，抽取等同层数的牌。",
        ["SHIRUBIMOD_POWER_SHIBI_STUNNED_ENEMY_THIS_TURN_POWER.title"] = "击晕记录",
        ["SHIRUBIMOD_POWER_SHIBI_STUNNED_ENEMY_THIS_TURN_POWER.description"] = "本回合击晕过敌人。",
        ["SHIRUBIMOD_POWER_SHIBI_STUNNED_ENEMY_THIS_COMBAT_POWER.title"] = "击晕记录",
        ["SHIRUBIMOD_POWER_SHIBI_STUNNED_ENEMY_THIS_COMBAT_POWER.description"] = "本场战斗击晕过敌人。",
        ["SHIRUBIMOD_POWER_SHIBI_PLATED_ARMOR_POWER.title"] = "覆甲",
        ["SHIRUBIMOD_POWER_SHIBI_PLATED_ARMOR_POWER.description"] = "每回合开始时，获得等同层数的[gold]格挡[/gold]，然后层数减少1。",
        ["SHIRUBIMOD_POWER_SHIBI_HARDENING_PATTERN_POWER.title"] = "硬化之纹",
        ["SHIRUBIMOD_POWER_SHIBI_HARDENING_PATTERN_POWER.description"] = "每回合开始获得[gold]格挡[/gold]。",
        ["SHIRUBIMOD_POWER_SHIBI_HEROIC_SEAL_POWER.title"] = "豪气之印",
        ["SHIRUBIMOD_POWER_SHIBI_HEROIC_SEAL_POWER.description"] = "每回合开始获得[gold]力量[/gold]。"
    };

    public static bool Prefix(string key, ref string __result)
    {
        // 如果不是希比 mod 的 key，就放行给游戏原本的 LocTable 处理。
        if (!Text.TryGetValue(key, out var text))
        {
            return true;
        }

        // 如果命中了希比 mod 的 key，就直接返回这里的文本，跳过原本的读取逻辑。
        __result = text;
        return false;
    }
}
